Добавлен параметр для обновления расширения из хранилища
silverbulleters/vanessa-runner pull request #310
Opened 2019-08-30 05:10 UTC by Borisskin

Не хватало параметра вызова, который уже есть в МенеджерКонфигуратора.ЗапуститьОбновлениеИзХранилища
При вызове runner loadrepo в cmd добавить параметр вызова, где NameExtension - имя расширения 
`call runner loadrepo --storage-ext "-Extension \"NameExtension\""`

2019-08-30 06:39 UTC, artbear requested changes
немного бы дополнить

2019-08-30 06:39 UTC, artbear commented on src/Классы/КомандаОбновитьИзХранилища.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--storage-ext",	"Доп. ключи запуска");
Предлагаю еще добавить спец. параметр "--extension" для указания имени расширения

и прокидывать его, передавая как еще один доп.параметр.

т.е. будет 2 новых параметра у команды.

в итоге код будет такой
```
ДопПараметры = СтрШаблон("%1 %2", ПараметрыКоманды["--extension"], ПараметрыКоманды["--storage-ext"]);
МенеджерКонфигуратора.ЗапуститьОбновлениеИзХранилища(
			ПараметрыКоманды["--storage-name"], ПараметрыКоманды["--storage-user"],
			ПараметрыКоманды["--storage-pwd"], 
			ПараметрыКоманды["--storage-ver"]);
			ПараметрыКоманды["--storage-ver"], ДопПараметры);
```

2019-08-30 06:40 UTC, artbear commented on src/Классы/КомандаОбновитьИзХранилища.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--storage-ext",	"Доп. ключи запуска");
И получим простую команду
`call runner loadrepo --extension "NameExtension"`

2019-08-30 07:03 UTC, Borisskin commented on src/Классы/КомандаОбновитьИзХранилища.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--storage-ext",	"Доп. ключи запуска");
Чтобы сработало указание на расширение, необходимо в строке запуска из cmd добавить
-Extension "NameExtension"

Предлагаемый вариант с параметром --extension ведёт к тому, что надо дополнительно изменить код в МенеджерКонфигуратора.ЗапуститьОбновлениеИзХранилища и там обрабатывать параметр, и если он не пусто добавлять к строке запуска "-Extension"
Или я не так понял предлагаемый вариант?

2019-09-09 11:54 UTC, Borisskin commented on src/Классы/КомандаОбновитьИзХранилища.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--storage-ext",	"Доп. ключи запуска");
Сейчас столкнулся с тем, что в КомандаОтключитьсяОтХранилища.os тоже не хватает параметра для указания расширения, как и для КомандаПодключитьсяКХранилищу.os.
И теперь согласен с тем, что надо вводить просто параметр для имени расширения.

Почему-то в других *.os параметр имени расширения объявлен как 'extensionName', без двойного дефиса в начале. Привести бы к общему объявлению параметра.

2019-12-13 12:18 UTC, artbear requested changes
есть много вопросов для обсуждения.
Обсудим/исправим?

2019-12-13 12:18 UTC, artbear commented on src/Классы/КомандаПодключитьсяКХранилищу.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--storage-name", "Строка подключения к хранилищу");
вот эти изменения поломают существующие команды и CI (

т.к. уходим от позиционных параметров к указанию имен.

2019-12-13 12:18 UTC, artbear commented on src/Классы/КомандаПодключитьсяКХранилищу.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--storage-name", "Строка подключения к хранилищу");
пока предлагаю параметры логина и пароля оставить позиционными, а имя расширения указать как именованный параметр.

2019-12-13 12:18 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +	Параметры.Добавить("-force ");
зачем нужны доп.пробелы в конце 2х ключей ??
- "/ConfigurationRepositoryUnbindCfg "
- "-force "

2019-12-13 12:18 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +		Лог.Информация("Выполняю отключение от хранилища расширения");
считаю неверной проверку на хранилище расширения выполнять через 
`Если Не ПустаяСтрока(ДополнительныеКлючиЗапуска)`

закладываем мину на будущее.
если в будущем добавятся другие доп.ключи, это условие будет неверным.

2019-12-13 12:18 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +		Лог.Информация("Выполняю подключение к хранилищу расширения");
и здесь считаю неверной проверку на хранилище расширения выполнять через 
`Если Не ПустаяСтрока(ДополнительныеКлючиЗапуска)`

закладываем мину на будущее.
если в будущем добавятся другие доп.ключи, это условие будет неверным.

2019-12-13 12:18 UTC, artbear commented on src/Классы/КомандаПодключитьсяКХранилищу.os
> +		ДопПараметры = "-Extension """+ИмяРасширения+"""";
использование спрятанных доп.параметров в виде строки считаю нехорошим кодом для передачи в АПИ-функции МенеджераКонфигуратора.

Предлагаю к методам
- МенеджерКонфигуратора.ПодключитьсяКХранилищу
- МенеджерКонфигуратора.ОтключитьсяОтХранилища
либо
- добавить по одному параметру ИмяРасширения
- либо сделать спец.методы - **это лучшее**
- МенеджерКонфигуратора.ПодключитьсяКХранилищуРасширения
- МенеджерКонфигуратора.ОтключитьсяОтХранилищаРасширения

это же АПИ, его удобнее разделять.

2019-12-13 12:51 UTC, artbear commented
В общем, давай обсудим, исправим и включим в следующий релиз.

в релиз 1.9.0 не вошло из-за вопросов (

2019-12-17 05:56 UTC, artbear commented
@Borisskin обсудим?

2019-12-17 06:00 UTC, Borisskin commented
Привет. Извини, загруженные дни были. Сегодня вечером посмотрю и отвечу.

вт, 17 дек. 2019 г., 8:56 Artur Ayukhanov <notifications@github.com>:

> @Borisskin <https://github.com/Borisskin> обсудим?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/silverbulleters/vanessa-runner/pull/310?email_source=notifications&email_token=AAXXCTOMINROAR6YDVDH7Y3QZBSZXA5CNFSM4ISJJN22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHBHYBI#issuecomment-566393861>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXXCTPMYC3WIY3FRGZ4J4DQZBSZXANCNFSM4ISJJN2Q>
> .
>

2019-12-17 07:38 UTC, Smilebringer commented
Привет, еще придется модифицировать команду обновления БД. Ловлю такой момент, что при вызове updatedb не обновляет расширение. Думаю связано с тем, что без явного указания имени расширения обновляется только основная конфигурация

2019-12-17 07:44 UTC, Smilebringer commented
Отбой, поторопился, платформенная бага
[https://bugboard.v8.1c.ru/error/000046991](url)

2019-12-18 07:33 UTC, Borisskin commented on src/Классы/МенеджерКонфигуратора.os
> +	Параметры.Добавить("-force ");
Тут перемудрил и пробелы, действительно, лишние

2019-12-18 07:46 UTC, Borisskin commented on src/Классы/КомандаПодключитьсяКХранилищу.os
> +		ДопПараметры = "-Extension """+ИмяРасширения+"""";
Т.к. не сильно разбираюсь, то и не понимаю полезности разделения методов, т.к. из-за одного параметра добавленного, потом поддерживать надо уже 2 метода одного направления. 
Пока (лично) выбираю добавление параметра ИмяРасширения к методам:
- МенеджерКонфигуратора.ОтключитьсяОтХранилища
- МенеджерКонфигуратора.ПодключитьсяКХранилищу
- МенеджерКонфигуратора.ЗапуститьОбновлениеИзХранилища

Либо, когда в озвученных командах встречает параметр ИмяРасширения, то можно вызывать в МенеджерКонфигуратора метод для Расширения. Ты это имел в виду?

2019-12-18 08:55 UTC, Borisskin commented on src/Классы/МенеджерКонфигуратора.os
> +	Параметры.Добавить("-force ");
Почему в МенеджерКонфигуратора.ПодключитьсяКХранилищу для подключения используется МенеджерХранилищаКонфигурации, а не сразу УправлениеКонфигуратором?
Первый не принимает имя расширения, его дописывать надо. Во второй же просто добавить параметр на выполнение.
Как раз из-за CI?

2020-01-08 06:48 UTC, PavelDv commented
МенеджерКонфигуратора.os, строка 559
Переменная логинАдминистратора не объявлена. Просто Логин.

2020-02-29 14:04 UTC, artbear commented
@Borisskin сейчас в твоем ПР возник конфликт кода.

1 исправишь?
2 можешь добавить простое минимальное хранилище расширения
  - в нем 2 коммита для расширения
  - расширение простейшее для базы Ванесса-АДД (83Sync) - добавлен новый отчет, например

а я бы на основании этого расширения сделал бы фичи для проверки твоего кода

хочется включить твой ПР в текущий релиз, как и обещал )
очень жду.

2020-07-06 09:26 UTC, Borisskin commented
На этой неделе сильно занят, если не получится, то на следующей точно сделаю.

2020-07-30 04:20 UTC, Borisskin commented
Автоматом коммит сюда, а не в #391.
Не сверял, но ключей для параметра расширения можно много реализовать: [обсуждение на инфостарт](http://forum.infostart.ru/forum24/topic234969/message2381166/#message2381166)

2025-07-24 14:03 UTC, Segate-ekb commented
@Borisskin  Пр еще актуален? Или можно его закрыть? ) 
последнее изменение 3 года назад...

2025-07-24 14:38 UTC, Borisskin commented
> @Borisskin  Пр еще актуален? Или можно его закрыть? ) 
> последнее изменение 3 года назад...

Я думаю можно закрыть. Первые комментарии были 5 лет назад. Оно даже в дев не попадало. А где я это использовал я там полгода уже не работаю.

2025-07-25 07:26 UTC, closed without merging