Инкриментальная загрузка на основании расхождений не только с предыдущим коммитом, но и с текущей конфигурацией
silverbulleters/vanessa-runner pull request #629
Opened 2024-10-03 07:14 UTC by Segate-ekb

В текущем алгоритме работы флага --git-increment есть несколько проблем:
1) Если изменения внесены в worktree(Например в vscode исправлены замечания сонара) при попытке обновить через инкремент - эти изменения будут проигнорированы
2) Если в конфигурации есть изменения, которых нет в гит, то загрузка никак их не учитывает, и в лучшем случае, они просто останутся в конфигурации(и потом попадут как мусорные изменения), в худшем случае - часть изменений останется, а часть будет изменена(из-за пересечения по файлам)

Данный пр меняет логику работы флага и добавляет трекинг изменеий внутри конфигурации с момента последней загрузки,
А так же трекинг изменений сделанных в worktree

2024-10-11 10:28 UTC, artbear commented on src/Классы/МенеджерIbcmd.os
> +ПутьКФайлуИзменений = ОбъединитьПути(КаталогВыгрузки, "diff.txt");
нет отступов

2024-10-11 10:33 UTC, artbear commented on src/Классы/МенеджерIbcmd.os
> +Функция ПолучитьИзмененияКонфигурации(Знач КаталогВыгрузки,
описание публичной части

2024-10-11 10:35 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +
убрать ненужные изменения пробельных символов

2024-10-11 10:37 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +		Знач ФорматВыгрузки = "") Экспорт
в 2х файлах МенеджерХХХ у этого метода разное количество параметров.

договорились убрать параметр ФорматВыгрузки для универсальности

2024-10-30 09:03 UTC, Segate-ekb commented on src/Классы/МенеджерIbcmd.os
> +Функция ПолучитьИзмененияКонфигурации(Знач КаталогВыгрузки,
fix

2024-10-30 09:12 UTC, Segate-ekb commented on src/Классы/МенеджерКонфигуратора.os
> +		Знач ФорматВыгрузки = "") Экспорт
fix

2024-11-04 08:58 UTC, artbear requested changes

2024-11-04 08:58 UTC, artbear commented on tasks/test.os
> -КонецЕсли;
почему так сделано? если запускать в обычном режиме, из командной строки для проверки, то не будет падения у контрибьютора, разработчика

давай выделим отдельной ключ командной строки, при котором не будет падения
- без доп.ключей как сейчас, выброс исключение
- со спец.ключом исключения не будет

2024-11-04 08:58 UTC, artbear commented on tasks/unit-test.os
> +УстановитьТекущийКаталог(ТекКаталог);
и здесь желательно добавить падение скрипта при неудаче, а не просто сообщение

можно разрулить аналогично через доп.ключ командной строки

2024-11-04 09:13 UTC, artbear commented on tasks/test.os
> -КонецЕсли;
давай так для ускорения и упрощения
1 ты код вызова исключения просто комментируешь вместо удаления 
2 и добавляешь комментарий перед кодом, что-то вроде - 
`если нужен другой код возврата вместо 0, то верните вызов исключения`

2024-11-04 19:25 UTC, closed without merging