Реализация использования ibcmd для серверных баз
silverbulleters/vanessa-runner pull request #639
Opened 2024-11-08 06:47 UTC by Segate-ekb

Создал новый ПР, потому что в старом был мусор.

Для команд использующих ibcmd добавлены новые параметры:
СУБД_Тип "--dbms-type"
СУБД_Сервер "--dbms-server"
СУБД_База "--dbms-base"
СУБД_Пользователь "--dbms-user"
СУБД_Пароль "--dbms-pwd"
Так же доступны соответствующие переменные окружения:

RUNNER_DBMS_USER
RUNNER_DBMS_PWD
RUNNER_DBMS_TYPE
RUNNER_DBMS_SERVER
RUNNER_DBMS_BASE
Убрана заглушка на обработку серверных баз с помощью ibcmd

Добавил информацию об ibcmd в схему json

2024-11-08 12:23 UTC, artbear requested changes

2024-11-08 12:23 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +КонецФункции
добавь отступы слева для всех строк метода

2024-11-08 12:23 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	ПриведенноеЗначение = Значение;
метод не очень точный. если значение любого типа, кроме Строки и Числа, вернется именно это значение, а не булевый вариант

например, для Неопределено вернется Неопределено, а не булево

2024-11-08 12:23 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +		Иначе
изменена логика этого метода - теперь происходит БЕЗУСЛОВНАЯ замена значения в основной коллекции по ключу, неважно, если этот ключ в доп.коллекции или нет 

не согласен с этим

весь смысл метода в дополнении основной коллекции - если в основной коллекции нет значения, то подставляется значение из доп.коллекции
поэтому в названии и указано слово "приоритет" - значение в основной важнее, чем во вспомогательной

получается, что теперь нет смешивания значений из разных коллекций, есть безусловная замена на значения из последней доп.коллекции

2024-11-08 12:25 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +		Иначе
видимо, не хватает тестов, которые покажут смешивание параметров из разных наборов - ком.строка, файл, переменная окружения

и зафиксируют приоритеты, порядок использования этих наборов

2024-11-08 12:50 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +	ПриведенноеЗначение = Значение;
Чисто в теории - мы используем это для операций с конфигами, там нет ничего кроме строки булева и числа. Как я это себе представлял

2024-11-08 12:58 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +		Иначе
Данный метод использовался для обогащения коллекций, но по разному.

Сейчас он используется ровно одинаково везде. Отсюда - стало проще, несмотря на то что функционал сохранился.

Раньше мы пытались собрать от максимального приоритета - к минимальному. т.е. брали Готовую коллекцию и пытались ее обогатить, что очень плохо работает с булевом.

Сейчас у нас последовательно читаются Общие настройки из env-> настройки команды из env -> переменные окружения -> аругменты из командной строки.

т.к. каждый следующий уровень - более приоритетный, у нас можно спокойно вызывать безусловное заполнение параметров.(потому что встретили - значит надо заполнить. Всегда)

2024-11-08 19:31 UTC, artbear requested changes

2024-11-08 19:31 UTC, artbear commented on src/Классы/МенеджерIbcmd.os
> +		Лог.Отладка("Установим контекст файловой ИБ");
ДанныеПодключения.ПутьБазы повторяются в этом методе . предлагаю использовать переменную СтрокаПодключенияИБ

2024-11-08 19:31 UTC, artbear commented on vanessa-runner-schema.json
> +                    "id": "/properties/default/properties/--nocacheuse",
копипаст, неверное описание флага

2024-11-08 19:31 UTC, artbear commented on vanessa-runner-schema.json
> +                    "id": "/properties/default/properties/--nocacheuse",
и здесь ошибка описания флага, похоже

2024-11-08 19:31 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип сервера СУБД");
скорее, тип ограничен коротким списком, и лучше в подсказку указать все варианты

легче будет пользоваться параметром и не бегать в справку ibcmd

2024-11-09 08:13 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип сервера СУБД");
fix

2024-11-09 08:13 UTC, Segate-ekb commented on vanessa-runner-schema.json
> +                    "id": "/properties/default/properties/--nocacheuse",
fix

2024-11-09 08:13 UTC, Segate-ekb commented on vanessa-runner-schema.json
> +                    "id": "/properties/default/properties/--nocacheuse",
fix

2024-11-09 08:13 UTC, Segate-ekb commented on src/Классы/МенеджерIbcmd.os
> +		Лог.Отладка("Установим контекст файловой ИБ");
fix

2024-11-10 10:04 UTC, artbear requested changes

2024-11-10 10:04 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +ПолучитьЛог();
верни перевод строки после последней строки файла. гитхаб на это указывает.

2024-11-10 10:04 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения:
в таком варианте строка подсказки слишком удлиняется и меньше шансов уместиться на экране пользователя

выведи все значения в одну строку 
`Тип СУБД. Разрешенные значения: MSSQLServer, PostgreSQL, IBMDB2, OracleDatabase`

2024-11-10 10:04 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения:
еще вопрос - значения типов регистрозависимы или нет?

2024-11-10 10:04 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения:
а еще лучше упростить написание - убрать малозначащие дополнения и оставить простые ключи
пользователям команд будет легко и просто задавать типы без необходимости подглядывать в подсказку

`Тип СУБД. Разрешенные значения: MSSQL, PostgreSQL, DB2, Oracle`

2024-11-10 10:04 UTC, artbear commented on vanessa-runner-schema.json
> +                    "description": "Тип СУБД. Разрешенные значения:\n   * MSSQLServer\n   * PostgreSQL\n   * IBMDB2\n   * OracleDatabase\n",
если будем упрощать ключи, значения нужно и здесь, в описании поменять

и ниже, в перечислении

2024-11-10 10:04 UTC, artbear commented on vanessa-runner-schema.json
> +                    "enum": ["MSSQLServer", "PostgreSQL", "IBMDB2", "OracleDatabase"]
если будем упрощать ключи, значения нужно и здесь, в описании поменять

и в перечислении

2024-11-10 10:07 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения:
Тут идёт прямая трансляция в ibcmd и это бъётся с тем, что есть на ИТС. Тут я бы не стал менять

2024-11-11 09:30 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения:
Теперь регистронезависимы везде.

2024-11-11 10:40 UTC, artbear requested changes

2024-11-11 10:40 UTC, artbear commented on src/Классы/МенеджерIbcmd.os
> +	Если ВРег(ТипСУБД) = "MSSQLSERVER" ИЛИ ВРег(ТипСУБД) = "MSSQL" Тогда
глаз режет от куда `ВРег(ТипСУБД)`, копипаст - зло

выдели `ВРег(ТипСУБД)` в отдельной переменную Тип

2024-11-11 10:40 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения: MSSQLServer, PostgreSQL, IBMDB2, OracleDatabase"); // BSLLS:LineLength-off
сюда добавить и сокращенные варианты, раз уж все равно в коде добавлено их приведение

2024-11-12 06:46 UTC, Segate-ekb commented on src/Модули/ОбщиеМетоды.os
> +	Парсер.ДобавитьИменованныйПараметрКоманды(ОписаниеКоманды, "--dbms-type", "Тип СУБД. Разрешенные значения: MSSQLServer, PostgreSQL, IBMDB2, OracleDatabase"); // BSLLS:LineLength-off
fix

2024-11-12 06:46 UTC, Segate-ekb commented on src/Классы/МенеджерIbcmd.os
> +	Если ВРег(ТипСУБД) = "MSSQLSERVER" ИЛИ ВРег(ТипСУБД) = "MSSQL" Тогда
fix

2024-11-12 13:05 UTC, merged