Рефакторинг работы с параметрами.
silverbulleters/vanessa-runner pull request #641
Opened 2024-11-08 14:27 UTC by Segate-ekb

2024-11-10 16:23 UTC, artbear requested changes

2024-11-10 16:23 UTC, artbear commented on src/Модули/МенеджерКомандПриложения.os
> +												НеявнаяЛожь = Ложь)
ненужный перенос параметр. сигнатура метода короткая, предлагаю все параметры разместить на одной строке

`Процедура ОбогатитьКоллекцию(КоллекцияОсновная, Знач КоллекцияДоп, НеявнаяЛожь = Ложь)`

2024-11-10 16:23 UTC, artbear commented on src/Модули/МенеджерКомандПриложения.os
> +		ПриведенноеЗначение = Значение;
как я писал в предыдущем ПР - это подозрительный вызов.

возможно, в фичах нужно проверить не только false, но и 0 и ложь, и тогда они упадут.

2024-11-10 16:23 UTC, artbear commented on src/Модули/МенеджерКомандПриложения.os
> +Функция ПодставитьЗначенияПеременныхСреды(СтрокаПодстановки)
полезного теста на эту функциональность, с подстановкой значений переменных среды, у нас нет. 

в Сонаре эти строки не покрыты.

2024-11-10 16:23 UTC, artbear commented on src/Модули/МенеджерКомандПриложения.os
> +Функция ПодставитьЗначенияПеременныхСреды(СтрокаПодстановки)
добавишь фичу? можно подставить переменную среды TEMP

2024-11-10 16:23 UTC, artbear commented on features/ПриоритетыНастроек.feature
> +# language: ru
нужно смержить ветку девелоп из гитхаба в ветку ПР, т.к. в девелоп эта фича дополнена.

2024-11-10 16:23 UTC, artbear commented on features/ПереопределениеНастроек.feature
> +# language: ru
предлагаю этот файл удалить, т.к. теперь у нас есть настоящая боевая фича по настройкам

2024-11-11 06:43 UTC, Segate-ekb commented on src/Модули/МенеджерКомандПриложения.os
> +		ПриведенноеЗначение = Значение;
Числа обрабатываются корректно,
Строки тоже.
т.к. на входе всегда json - то Ложь(булево) - тут быть не может, она не десериализуется из json. Но Даже если бы была - тоже нормально бы прошла.

Если что проверка на число - есть в тестах

2024-11-11 06:44 UTC, Segate-ekb commented on features/ПереопределениеНастроек.feature
> +# language: ru
ок.

2024-11-11 07:38 UTC, Segate-ekb commented on features/ПриоритетыНастроек.feature
> +# language: ru
fix

2024-11-11 07:38 UTC, Segate-ekb commented on features/ПереопределениеНастроек.feature
> +# language: ru
fix

2024-11-11 07:40 UTC, Segate-ekb commented on src/Модули/МенеджерКомандПриложения.os
> +												НеявнаяЛожь = Ложь)
fix

2024-11-11 08:59 UTC, Segate-ekb commented on src/Модули/МенеджерКомандПриложения.os
> +Функция ПодставитьЗначенияПеременныхСреды(СтрокаПодстановки)
fix

2024-11-11 10:47 UTC, artbear requested changes

2024-11-11 10:47 UTC, artbear commented on features/ПриоритетыНастроек.feature
> +# language: ru
нет, опять какая-то ересь, файл выглядит полностью как новый, что неверно

должна быть дифф-версия файла, т.к. в девелоп файл с таким же именем уже есть.

2024-11-11 10:47 UTC, artbear commented on features/ЗапуститьКонфигуратор.feature
> +        | ОШИБКА |
и здесь неверно, эти изменения есть в ветке девелоп, их не должно быть в этом ПР

2024-11-11 10:47 UTC, artbear commented on examples/example.env.json
> +        "--workspace": "./build/out",
и здесь неверно, эти изменения есть в ветке девелоп, их не должно быть в этом ПР

2024-11-11 10:55 UTC, artbear commented on src/Модули/МенеджерКомандПриложения.os
> +		ПриведенноеЗначение = Значение;
для ПР сейчас нет покрытия и нельзя сказать, покрывается ли эта строка тестами или нет (

похоже, что все-таки ветка девелоп неверно вмержена в текущую ветку

2024-11-11 11:01 UTC, closed without merging