[FEAT] Добавлен параметр ibsrv для запуска команд с использование автономного сервера
silverbulleters/vanessa-runner pull request #645
Opened 2024-11-13 15:34 UTC by yukon39

Добавлен параметр ibsrv для запуска команд с использование автономного сервера для команд:
* run
* vanessa
* xunit
* designer

Closes #619 

Требует изменений в библиотеке ibcmdrunner [PR #3](https://github.com/vanessa-opensource/ibcmdrunner/pull/3)

2024-11-13 18:38 UTC, Segate-ekb commented
У меня вопрос, а мы не хотим ас сделать поведением по умолчанию для ряда операций? Например тех, что требуют временную базу. Так можно избавиться от требования лицензии в ci) так ведь?

2024-11-16 10:52 UTC, artbear requested changes

2024-11-16 10:52 UTC, artbear commented on src/Классы/МенеджерIbsrv.os
> +#Использовать ibcmdrunner
@yukon39 пройдись, пожалуйста, по Сонару, поправь замечания

например, вот это важно, похоже, ошибка копипаста
- https://sonar.openbsl.ru/project/issues?rules=bsl-language-server%3ADuplicatedInsertionIntoCollection&issueStatuses=CONFIRMED%2COPEN&pullRequest=645&id=vanessa-runner

2024-11-16 10:52 UTC, artbear commented on src/Классы/МенеджерIbsrv.os
> +	КонфигурацияАС.ПараметрыСервера(СетевойИнтерфейс, ПортHttpДоступа);
точно ли верно передавать СетевойИнтерфейс = "any" как 1й параметр в метод КонфигурацияАС.ПараметрыСервера(СетевойИнтерфейс, ПортHttpДоступа);

ведь в описании этого метода написано - https://github.com/vanessa-opensource/ibcmdrunner/pull/3/files#diff-e0fb19d225ead947bba5276611a775f1f4fede191b18df6779c2738104e512a5R33

"Адрес - Строка - IP-адрес автономного сервера"
а здесь передается какая-то строка `any`, которая не является ип-адресом

2024-11-16 10:52 UTC, artbear commented on src/Классы/МенеджерIbsrv.os
> +	КонфигурацияАС.ПараметрыСервера(СетевойИнтерфейс, ПортHttpДоступа);
вместо КонфигурацияАС = Новый КонфигурационныйФайлАС;

стоит написать `КонфигурационныйФайлАС = Новый КонфигурационныйФайлАС;`

тогда плагин bsl ls для ВСКод сможет выдавать подсказки по методам и их параметрам для этой переменной

2024-11-16 10:52 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +Функция ВыполнитьКомандуСУчетомIbsrv(ПараметрыКоманды, Действие, ПараметрыАвтономногоСервера) Экспорт
нет описания публичного метода

2024-11-16 10:52 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	МенеджерIbsrv.Конструктор(ДанныеПодключения, ПараметрыКоманды);
подозрительный метод Конструктор, который вызывается сразу же после реального создания\конструирования объекта. псевдо-метод

предлагаю код этого метода переместить в код метода ПриСоздании класса МенеджерIbsrv
- и добавить оба параметра Конструктора в метод ПриСоздании

2024-11-16 10:52 UTC, artbear commented on src/Модули/ОбщиеМетоды.os
> +	МенеджерIbsrv.Конструктор(ДанныеПодключения, ПараметрыКоманды);
тем более, что метод Конструктор служебный, но является публичным, хотя находится в секции служебных методов

в общем, он выглядит как явно лишний метод

2024-11-18 13:56 UTC, yukon39 commented on src/Классы/МенеджерIbsrv.os
> +	КонфигурацияАС.ПараметрыСервера(СетевойИнтерфейс, ПортHttpДоступа);
Точно. Надо наверно тогда уточнить описание метода - допустимы IP адреса, DNS псевдонимы, а также два специальных литерала "localhost" и "any"

2024-11-18 13:59 UTC, yukon39 commented on src/Модули/ОбщиеМетоды.os
> +	МенеджерIbsrv.Конструктор(ДанныеПодключения, ПараметрыКоманды);
по аналогии с Конструктор у менеджера Конфигуратора. В целом, да, это просто для единообразия. Менеджер Конфигуратора можно в отдельном PR отрефакторить - там это я так понимаю историческое наследие.

2024-11-18 14:41 UTC, yukon39 commented on src/Классы/МенеджерIbsrv.os
> +	КонфигурацияАС.ПараметрыСервера(СетевойИнтерфейс, ПортHttpДоступа);
исправлено

2024-11-19 09:38 UTC, Segate-ekb commented
У нас в конвейере начали падать тесты. 
У меня локально вот так:
![image](https://github.com/user-attachments/assets/8af53bba-d096-40cd-af4d-ab6528d82728)
Подозреваю, что внутри примерно то же самое, потому все висит и не завершается...

Надо с этим что-то решать )

2024-11-22 10:52 UTC, Segate-ekb commented
@yukon39 Обновили ci, добавив другие платформы, ребейзни пожалуйста )

2024-11-23 13:33 UTC, yukon39 commented
@artbear Добавил шаг сборки проекта в ci - собственно ошибка у @Segate-ekb возникает, т.к. проект банально не собран еще, и указанных обработок действительно нет в указанном месте.

Реализовать отдельным PR?

2024-11-23 14:25 UTC, artbear requested changes

2024-11-23 14:25 UTC, artbear commented on src/Классы/МенеджерIbsrv.os
> +			Лог.Отладка("Разрядность платформы 1С не указана");
предлагаю чуть улучшить сообщение "Разрядность платформы 1С не указана, использую разрядность x64x86"

2024-11-23 14:25 UTC, artbear commented on src/Классы/МенеджерКонфигуратора.os
> +	ТекстВывода = ВыводПредприятия(ПутьДамп);
потеряно возвращаемое значение метода. скорее всего, переменную ТекстВывода в этом месте и дальнейшее ее использование нужно переименовать в Результат

и тогда вызов Возврат Результат в конце метода отработает верно

2024-11-23 14:25 UTC, artbear commented on src/Классы/КомандаЗапуститьВРежимеПредприятия.os
> +	ПутьОбработкиДляЗапуска = ПолучитьПроверитьПутьОбработкиДляЗапуска(ПараметрыКоманды);
предлагаю чуть улучшить код

`Функция ПутьОбработкиДляЗапуска(Знач ПутьОбработки1С)`

передавать ПараметрыКоманды не нужно, зачем лишние связи для этого довольно простого метода,
вызывать через 
`ПутьОбработкиДляЗапуска = ПутьОбработкиДляЗапуска(ПараметрыКоманды["--execute"]);`

2024-11-23 15:33 UTC, Segate-ekb commented
> @artbear Добавил шаг сборки проекта в ci - собственно ошибка у @Segate-ekb возникает, т.к. проект банально не собран еще, и указанных обработок действительно нет в указанном месте.
> 
> Реализовать отдельным PR?

Вот я не знаю... у меня паттерн разработки - далеко не всегда зависит от предварительной сборки проекта. Мне кажется, что когда у тебя есть кнопка "Запустить тест", она должна выполнять тест... 
Тем более, что мы не тестируем обработку, которая у нас в требованиях, и значит, в теории, вообще не должны ее собирать.
Не совсем понимаю, если мы не тестируем в данном тесте обработку, то почему не засунуть ее в фикстуры? Ну или в конце концов не собирать отдельно, если не нашли по нужному пути?

2024-12-04 14:22 UTC, closed without merging

2024-12-04 14:22 UTC, artbear commented
ПР фактически смержен в https://github.com/vanessa-opensource/vanessa-runner/commit/d4ec54b10e9b4142e6c8697db04f2e3144c06938
- закрываю его

@yukon39 большое спасибо тебе за доработку и за терпение!
в описании релиза отмечу тебя как автора!